### ISSUE TITLE
Dedicated server inconsistencies

### ISSUE THREAD

**Issue by cadenkriese** [Qendolin/boat-step-up#1]
# Summary
Minecraft handles boat movement mechanics client-side, which is what the mod targets. However, this means that a player with the mod can use it on a vanilla server. Furthermore, the player can configure the mod to go up one or multiple blocks, as seen in the example below.

https://user-images.githubusercontent.com/13630061/144823622-98ec818f-393c-449c-9887-1eb397be2ca9.mp4

It's also worth noting that the opposite does not work; the mod being installed on the server does not affect the client.

**Comment by Qendolin** [comment]
This should be fixed in the latest release
