### ISSUE TITLE
Can't use config file

### ISSUE THREAD

**Issue by Rad586** [Qendolin/boat-step-up#2]
Game version: 1.18.2 fabric
Mod version: 1.2.1
Description:
Can‘t change anything in config file, everytime I restart the game, it turns back to it's default value.

**Comment by Qendolin** [comment]
Can you link a copy of your (entire) game log? There should be an error message somewhere.

**Comment by Rad586** [comment]
[changing ingame.txt](https://github.com/Qendolin/boat-step-up/files/10709145/changing.ingame.txt)
[next load.txt](https://github.com/Qendolin/boat-step-up/files/10709147/next.load.txt)


> Can you link a copy of your (entire) game log? There should be an error message somewhere.

**Comment by Qendolin** [comment]
Can you replace the mod with the version contained in this zip file and check if the issue persists?
[boat-step-up-1.2.2-beta.zip](https://github.com/Qendolin/boat-step-up/files/10709213/boat-step-up-1.2.2-beta.zip)

**Comment by Rad586** [comment]
> Can you replace the mod with the version contained in this zip file and check if the issue persists? [boat-step-up-1.2.2-beta.zip](https://github.com/Qendolin/boat-step-up/files/10709213/boat-step-up-1.2.2-beta.zip)

Fixed, thanks!
